{
 "title": "Default",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "total_group",
    "query": {
     "query": "query_result(scalar(    last_over_time(        count(            max_over_time(                docker_container_info{                    name=~\"grafana|prometheus|loki|promtail|blackbox|github|ip|fritz|pihole6|docker\"                }[5s]            ) >= 1        )[2m:]    )))"
    }
   },
   {
    "name": "healthy_group",
    "query": {
     "query": "query_result(scalar(    last_over_time(        count(            max_over_time(                docker_container_state{                    state=\"running\",                    name=~\"grafana|prometheus|loki|promtail|blackbox|github|ip|fritz|pihole6|docker\"                }[5s]            ) >= 1        )[2m:]    )))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fritz_dsl_status", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "PPPoE Link",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "fritz_ppp_connection_state", "legendFormat": "State" },
    {
     "expr": "fritz_wan_connection_uptime_seconds",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(probe_success{job=\"blackbox_icmp\", instance=\"9.9.9.9\"}[2s]) == bool 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fritz_wan_data_bytes_total{direction=~\"rx\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fritz_wan_data_bytes_total{direction=~\"tx\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count by (country_code) (ip_info{country_code=\"DE\"})) or on(country_code) (0 * sum by (country_code) (ip_info))",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Public IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ip_current_info" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(ip_info)" }
   ]
  },
  {
   "title": "WAN Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "# Download (rx)\r\nfritz_wan_datarate_bytes{direction=\"rx\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "# Upload (tx)\r\nfritz_wan_datarate_bytes{direction=\"tx\"}",
     "legendFormat": "Upload"
    },
    {
     "expr": "# Down max line (6.26 MB/s)\r\nvector(6262000)",
     "legendFormat": "Down [Max]"
    },
    {
     "expr": "# Up max line (2.55 MB/s)\r\nvector(2550000)",
     "legendFormat": "Up [Max]"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Download (rx)\r\nfritz_wan_datarate_bytes{direction=\"rx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Upload (tx)\r\nfritz_wan_datarate_bytes{direction=\"tx\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}